'use client';

import { useEffect, useState } from 'react';
import type { EvidenceItem } from '../data';

export function ContextCards({ chunks }: { chunks: EvidenceItem[] }) {
  const [expanded, setExpanded] = useState<string | null>(null);
  const [chipsShown, setChipsShown] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => setChipsShown(true), 500); return () => window.clearTimeout(timer); }, []);
  return <div className="evidence-section"><div className="section-header"><div><span className="text-[11px] text-ink-3">All chunks</span><span className="ml-2 inline-flex h-5 items-center rounded-md bg-inset px-1.5 text-[11px] font-medium text-ink-2 shadow-hairline">{chunks.length + 29}</span></div><span className="font-mono text-[10px] text-ink-3">weighted by decision impact</span></div><div className="evidence-list">{chunks.map((chunk, index) => { const isOpen = expanded === chunk.id; return <div className="evidence-card" key={chunk.id} style={{ animation: `fade-up 400ms cubic-bezier(0.23,1,0.32,1) ${index * 80}ms both` }}><button className="evidence-trigger" type="button" aria-expanded={isOpen} onClick={() => setExpanded(isOpen ? null : chunk.id)}><span className="evidence-index">0{index + 1}</span><span className="evidence-title"><span className="font-mono text-[9px] uppercase tracking-[.1em] text-ink-3">{chunk.category}</span><strong>{chunk.title}</strong></span><span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${chunk.tone === 'lime' ? 'bg-green-tint text-green' : chunk.tone === 'amber' ? 'bg-orange-tint text-orange' : 'bg-accent-tint text-accent-ink'}`}>{chunk.summary}</span><span className="evidence-chevron" aria-hidden="true">{isOpen ? '−' : '+'}</span></button><div className="evidence-source"><i />{chunk.source}</div>{isOpen && <p className="evidence-detail" style={{ animation: 'fade-in 200ms ease-out both' }}>{chunk.detail}</p>}<div className={`px-3 pb-3 pl-[46px] transition-opacity duration-300 ${chipsShown ? 'opacity-100' : 'opacity-0'}`}><span className="inline-flex h-6 items-center gap-1.5 rounded-full bg-inset px-2 text-[11px] font-medium text-ink-2 shadow-btn"><span className={`flex size-3.5 items-center justify-center rounded-[4px] text-[7px] font-bold text-white ${chunk.tone === 'lime' ? 'bg-green' : chunk.tone === 'amber' ? 'bg-orange' : 'bg-accent'}`}>{chunk.tone === 'lime' ? 'G' : chunk.tone === 'amber' ? 'G' : 'S'}</span>{chunk.source}</span></div></div>; })}</div></div>;
}
