'use client';

import { useState } from 'react';
import { LoadingState } from './LoadingState';

export function RecommendationCard({ loading, queued, dismissed, onQueue, onDismiss, onRestore }: { loading: boolean; queued: boolean; dismissed: boolean; onQueue: () => void; onDismiss: () => void; onRestore: () => void }) {
  const [alternatives, setAlternatives] = useState(false);
  if (dismissed) return <div className="bio-recommendation recommendation-slot flex items-center justify-between gap-4" aria-live="polite"><div><span className="font-mono text-[10px] text-ink-3">Recommendation hidden</span><p className="recommendation-title">The decision surface is clear.</p></div><button className="ui-button ui-button-ghost" onClick={onRestore}>Restore</button></div>;
  return <div className="bio-recommendation recommendation-slot" aria-labelledby="rec-title"><div className="recommendation-head"><span className="font-mono text-[10px] uppercase tracking-[.11em] text-accent-ink">✦ AI recommendation</span><span className="recommendation-confidence"><i />High confidence</span></div><p className="recommendation-title" id="rec-title">Run a paired perturbation + rescue study</p><p className="recommendation-copy">Test target specificity in donor-derived epithelial cells before increasing chemistry investment.</p><div className="recommendation-meta"><span><span>Impact</span><strong>High</strong></span><span><span>Closes</span><strong>Translation gap</strong></span><span><span>Route</span><strong>External lab</strong></span></div><div className="mb-3 flex flex-wrap gap-1.5"><span className="source-chip"><i />Donor-derived model</span><span className="source-chip"><i style={{ background: 'var(--orange)' }} />Uncertainty resolver</span><span className="source-chip"><i style={{ background: 'var(--green)' }} />AX-014</span></div>{loading ? <LoadingState /> : <div className="recommendation-actions"><button className="ui-button ui-button-primary" onClick={onQueue}>{queued ? 'Experiment queued' : 'Queue experiment'} <span aria-hidden="true">→</span></button><button className="ui-button ui-button-quiet" onClick={onDismiss}>Dismiss</button><button className="ui-button ui-button-quiet ml-auto" onClick={() => setAlternatives(!alternatives)} aria-expanded={alternatives}>Alternatives <span aria-hidden="true">⌄</span></button></div>}{alternatives && <div className="mt-3 rounded-control bg-inset p-2 shadow-hairline"><div className="flex items-center justify-between px-2 py-1 text-[11px] text-ink-2"><span>Replicate dependency screen</span><span className="text-ink-3">Needs review</span></div><div className="flex items-center justify-between px-2 py-1 text-[11px] text-ink-2"><span>Wait for pathway time course</span><span className="text-ink-3">Lower impact</span></div></div>}</div>;
}
