import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import DecisionRecord from '@/components/DecisionRecord';
import DiscoveryPipeline from '@/components/DiscoveryPipeline';
import { decisionFlow, decisionRecord, gatingUncertainty, initialEvidence, initialExperiments, program } from '@/data';

export default function CompanyMode({ onBack }: { onBack: () => void }) {
  return <div className="company-mode-shell"><header className="company-mode-header"><div><p className="research-eyebrow">Secondary Company mode · illustrative fixture</p><h1>{program.code} program cockpit</h1><p>Preserved from the original Frontier Bio workspace. Research mode is the active product surface.</p></div><Button variant="outline" onClick={onBack}>Back to Research mode</Button></header><div className="company-mode-grid"><Card className="workspace-card"><CardHeader className="workspace-card-header"><div><p className="workspace-kicker">Gating uncertainty</p><CardTitle>{gatingUncertainty.title}</CardTitle></div><Badge variant="destructive">High uncertainty</Badge></CardHeader><CardContent><p className="company-copy">{gatingUncertainty.body}</p><p className="company-copy">This preserved cockpit is illustrative program context, not a clinical or operational recommendation.</p></CardContent></Card><Card className="workspace-card"><CardHeader className="workspace-card-header"><div><p className="workspace-kicker">Evidence fixture</p><CardTitle>What the program knows</CardTitle></div><Badge variant="outline">{initialEvidence.length} items</Badge></CardHeader><CardContent><div className="company-evidence-list">{initialEvidence.map((item) => <div key={item.id}><strong>{item.title}</strong><span>{item.summary} · {item.source}</span></div>)}</div></CardContent></Card></div><DiscoveryPipeline stages={decisionFlow.map((stage) => ({ label: stage.label, caption: stage.caption, status: stage.state === 'active' ? 'active' : stage.state === 'complete' ? 'complete' : 'next' }))} /><Card className="workspace-card"><CardHeader className="workspace-card-header"><div><p className="workspace-kicker">Decision-critical work</p><CardTitle>Experiment queue</CardTitle></div><Badge variant="outline">{initialExperiments.length} candidates</Badge></CardHeader><CardContent><div className="company-experiments">{initialExperiments.map((experiment) => <div key={experiment.id}><strong>{experiment.title}</strong><span>{experiment.assay} · {experiment.status}</span><Badge variant={experiment.status === 'queued' ? 'default' : 'secondary'}>{experiment.decisionImpact}/10</Badge></div>)}</div></CardContent></Card><DecisionRecord {...decisionRecord} /></div>;
}
